version: '3.8'
services:
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      CONN_STRING: root:1234@tcp(db:3306)/igaming?parseTime=true
      SERVER_ADDRESS: :8081
      CONTEXT_TIMEOUT: 2
      ACCESS_TOKEN_EXPIRY_HOUR: 2
      REFRESH_TOKEN_EXPIRY_HOUR: 168
      ACCESS_TOKEN_SECRET: access_token_secret
      REFRESH_TOKEN_SECRET: refresh_token_secret

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "igaming"
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
