basePath: /
host: localhost:8081
info:
  contact: {}
  description: API documentation for the iGaming Platform
  title: iGaming Platform API
  version: "1.0"
paths:
  /health:
    get:
      description: Just returns OK
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Health Check
      tags:
      - test
swagger: "2.0"
